site_name: Schulung 28.09.2023
dev_addr: '0.0.0.0:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
theme:
  name: material
  language: de
  font: false
  favicon: \figures\favicon.png
  logo: \figures\favicon.png
  icon:
    admonition:
      info: material/alarm 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

site_author: "bszetdd it-systems"

extra_css:
    - css/extra.css

nav:
  - GitHub Actions: schulung_vs_cs/gh-actions.md
  - CICD gh-deploy: schulung_vs_cs/cicd_gh-deploy.md
  - Visual Studio und GitHub: schulung_vs_cs/visual_studio_github_cs.md